### ISSUE TITLE
search failed

### ISSUE THREAD

**Issue by gooly** [omegat-org/omegat#8]
Hi,

I (Win 64, OmegaT 3.6.0_1) was trying to use search and failed. Further below is the error code from the log:
This is what I did:
Ctrl-F to open the window.
I entered "Instrumente",
I checked (enabled) -Exact search, -In translation and -translated and -Auto-sync with Editor
I press "Search".
I can read: Nr of matching segments: 2
and I see 2 "Orphan segments" one with a green background - but in the Editor nothiing was changed - even if I double-click on one of the Orphan segments - nothing.  :(

This is copied from the log file:

```
12477: Info: Click on 'editFindInProjectMenuItem' menu item (LOG_MENU_CLICK)
12477: Error: Uncatched exception in thread [AWT-EventQueue-0]
12477: Error: java.lang.ArrayIndexOutOfBoundsException: 0
12477: Error: 	at 
org.omegat.gui.editor.EditorController.getSegmentBounds(EditorController.java:968) 

12477: Error: 	at 
org.omegat.gui.editor.EditorController.access$1200(EditorController.java:148) 

12477: Error: 	at 
org.omegat.gui.editor.EditorController$14.run(EditorController.java:948)
12477: Error: 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
12477: Error: 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
12477: Error: 	at java.awt.EventQueue.access$500(Unknown Source)
12477: Error: 	at java.awt.EventQueue$3.run(Unknown Source)
12477: Error: 	at java.awt.EventQueue$3.run(Unknown Source)
12477: Error: 	at java.security.AccessController.doPrivileged(Native 
Method)
12477: Error: 	at 
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown 
Source)
12477: Error: 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
12477: Error: 	at 
java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
12477: Error: 	at 
java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
12477: Error: 	at 
java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
12477: Error: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
12477: Error: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
12477: Error: 	at java.awt.EventDispatchThread.run(Unknown Source)
12477: Info: Event: new entry activated (LOG_INFO_EVENT_ENTRY_ACTIVATED)
12477: FINER: Time for find matches: 31
12477: Info: Event: new file activated (7108split.html) 
(LOG_INFO_EVENT_ENTRY_NEWFILE)
12477: Info: Event: new entry activated (LOG_INFO_EVENT_ENTRY_ACTIVATED)
12477: FINER: Time for find matches: 28
12477: Info: Project saving start (LOG_DATAENGINE_SAVE_START)
12477: FINE: Disable autosave
12477: Info: No need to save project, because no changes were made 
(LOG_DATAENGINE_SAVE_NONEED)
12477: FINE: Enable autosave
12477: Info: Project saving end (LOG_DATAENGINE_SAVE_END)
12477: Info: Event: application shutdown 
(LOG_INFO_EVENT_APPLICATION_SHUTDOWN)
12477: Info: Event: project change - "SAVE" (LOG_INFO_EVENT_PROJECT_CHANGE)
```

**Comment by amake** [comment]
Orphaned segments can't show up in the Editor by definition. If your only results are orphans then there doesn't appear to be an issue.

The stack trace is basically unrelated, though I have addressed it in release-3-6 and trunk.

**Comment by amake** [comment]
I know it's not explicitly written anywhere, and we need to be more clear about this, but we would prefer that you report issues on SourceForge (https://sourceforge.net/p/omegat/bugs/new/) and not GitHub, as this project is merely a mirror.

I will close this issue as I don't think there is a bug. If you disagree, please re-open on SourceForge.
